/*
* generated by Xtext
*/
package de.jevopi.mitra2.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class MitraOutlineTreeProvider extends DefaultOutlineTreeProvider {
	// make manual customization 
}
