/*
 * generated by Xtext
 */
package de.jevopi.mitra2;

import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.naming.IQualifiedNameConverter;
import org.eclipse.xtext.util.CancelIndicator;
import org.eclipse.xtext.validation.IResourceValidator;
import org.eclipse.xtext.validation.ResourceValidatorImpl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MitraRuntimeModule extends de.jevopi.mitra2.AbstractMitraRuntimeModule {
	

	// contributed by org.eclipse.xtext.generator.exporting.SimpleNamesFragment
	/** 
	 * @see de.jevopi.mitra2.AbstractMitraRuntimeModule#bindIQualifiedNameProvider()
	 */
	@Override
	public Class<? extends org.eclipse.xtext.naming.IQualifiedNameProvider> bindIQualifiedNameProvider() {
		return MitraNameProvider.class;
	}
	
	
	/**
	 * 
	 */
	public MitraRuntimeModule() {
		
	}


	public Class<? extends IQualifiedNameConverter> bindIQualifiedNameConverter() {
		return MitraQualifiedNameConverter.class;
	}

		
	

	public Class<? extends IResourceValidator> bindIResourceValidator() {
		return MyResourceValidator.class;
	}
	
	public static class MyResourceValidator extends ResourceValidatorImpl {
		/**
		 * 
		 */
		public MyResourceValidator() {
			
		}
		
		@Override
		protected void resolveProxies(final Resource resource, final CancelIndicator monitor) {
			EcoreUtil2.resolveAll(resource, monitor);
		}

	}
	
	
}
